### ISSUE TITLE
Not all Tags on Workflow creation visible

### ISSUE THREAD

**Issue by SKB-CGN** [R0Wi/workflow_ocr#168] opened 2022-12-05 08:16 UTC
Hi,
i wanted to assign a tag-based file processing, but it only allows me, to select the first 5 ones.

![2022-12-05 09_14_36-Ablauf - Administrationseinstellungen - Kreyenborg koeln - Cloud — Mozilla Firef](https://user-images.githubusercontent.com/58603329/205587160-87fce4ab-d432-4a07-a1b0-689f0b557327.png)

![2022-12-05 09_15_07-Ablauf - Administrationseinstellungen - Kreyenborg koeln - Cloud — Mozilla Firef](https://user-images.githubusercontent.com/58603329/205587162-06f288b7-afe9-46b3-9373-98c0e1222094.png)

I checked, that i have the "ocr" tag created, but i am not able, to select it inside the workflow.
![2022-12-05 09_15_21-Grundeinstellungen - Administrationseinstellungen - Kreyenborg koeln - Cloud — M](https://user-images.githubusercontent.com/58603329/205587163-8caac9ea-2172-4d59-ac54-8c48313fff74.png)

**Comment by R0Wi** [comment] 2022-12-05 10:13
Related to https://github.com/nextcloud/nextcloud-vue/issues/2884. Seems like we have to update `nextcloud/vue` to at least `v6.0.0`

https://github.com/R0Wi/workflow_ocr/blob/dcb36015ca785d6047597bb796e44f220e7d7f60/package.json#L28

**Comment by SKB-CGN** [comment] 2022-12-05 10:16
This is something dev-related, i guess.
How can i "fix" this now?

**Comment by R0Wi** [comment] 2022-12-05 10:27
Since the issue is related to the Nextcloud Vue component `MultiselectTags`, unfortunately there is currently no workaround.

BTW.: I saw you're talking about the "triggers and conditions section" of the flow engine. These controls do not belong to this app, they're part of the NC workflow engine:

![image](https://user-images.githubusercontent.com/19730957/205613442-5692d3fa-b6af-45f7-81f5-ce38cf43b164.png)

Did a quick research and it seems like the engine itself uses `v5.3.1` for Nextcloud 24 (https://github.com/nextcloud/server/blob/stable24/package.json) and `v7.0.0` for Nextcloud 25 (https://github.com/nextcloud/server/blob/v25.0.1/package.json#L48). So updating to NC25 should fix the issue. If that's no option for you, please raise an issue at https://github.com/nextcloud/server/issues and ask for a backport.

Will close this for now since it is not directly related to this app. Please feel free to reopen if needed.

**Closed by R0Wi** 2022-12-05 10:27 UTC
Labels: bug, backport stable25
