### ISSUE TITLE
pdf size blows up

### ISSUE THREAD

**Issue by edd--** [R0Wi/workflow_ocr#37] opened 2020-11-13 13:37 UTC
Hi,

I'be noticed that the pdf size after running the workflow is much bigger than the source.

original: 268K scan_003298.pdf
after workflow:  2.6M scan_003298.pdf

this is almost x10, I'm using this for multipage pdf's and this results in pdf files of over 100 MB.

Maybe the compression was forgotten in imagemagick or something similar ?

**Comment by edd--** [comment] 2020-11-13 14:38
OK, found it:

in custom_apps/workflow_ocr/lib/OcrProcessors/PdfOcrProcessor.php

```
// Use Imagick to convert the pdf page to jpg
                                $img = $this->wrapperFactory->createImagick();
                                $img->setOption('density', '300');
                                $img->setOption('compress', 'JPEG');
                                $img->setOption('quality', '20');
                                $img->readImageBlob($onePagePdf);
                                $img->setImageFormat("jpg");
```

**Comment by R0Wi** [comment] 2020-11-13 15:07
Duplicate of https://github.com/R0Wi/workflow_ocr/issues/22 , will be fixed with the usage of `OCRmyPDF` https://github.com/R0Wi/workflow_ocr/issues/32

**Closed by R0Wi** 2020-11-13 15:07 UTC
