### ISSUE TITLE
error setting up the flow

### ISSUE THREAD

**Issue by Edzilla2000** [R0Wi/workflow_ocr#41] opened 2020-12-14 17:15 UTC
Hello, 
If I try to set up a flow where the OCR happens on create/update with mime type "PDF", I get a "the given regular expression is invalid" error:
![image](https://user-images.githubusercontent.com/5339038/102112703-5fb94480-3e38-11eb-9278-dd7691c16434.png)

**Comment by bahnwaerter** [comment] 2020-12-14 17:39
Thanks for reporting this error. I also observed this error a few weeks ago during testing (see https://github.com/R0Wi/workflow_ocr/issues/32#issuecomment-715596849).

This error is caused by a bug in the Nextcloud workflow engine. Therefore, @R0Wi reported this issue already to the Nextcloud server repository (see https://github.com/nextcloud/server/issues/23666#issue-728784474). We hope that this bug in the Nextcloud workflow engine will be fixed soon.

To get the OCR processing done, you can use the following temporary workaround. Replace the `matches` operator with the `is` operator and everything should work out fine.

**Comment by bahnwaerter** [comment] 2020-12-14 17:45
https://github.com/nextcloud/server/issues/23666#issue-728784474

**Comment by bahnwaerter** [comment] 2020-12-14 18:07
Duplicate of nextcloud/server#23666

**Comment by R0Wi** [comment] 2020-12-14 18:24
Thanks @Edzilla2000 and @bahnwaerter . Closing this sice this seems to be a problem inside NC core itself. Feel free to reopen if we can help somehow.

**Closed by R0Wi** 2020-12-14 18:24 UTC
Labels: bug, duplicate

**Comment by Niemand112233** [comment] 2020-12-31 13:58
I have the same problem, even if I select "is" instead of "matches".

**Comment by R0Wi** [comment] 2020-12-31 14:19
Unfortunately i cannot reproduce this issue (see attached screen video). Which version of Nextcloud do you use? And are you configuring "personal flows" (like me in the video) or "administration flows" (Settings -> Administration -> Flow) ?

https://user-images.githubusercontent.com/19730957/103413847-7f13d980-4b7b-11eb-8030-4f78dda467bf.mp4

**Comment by Niemand112233** [comment] 2021-01-02 13:57
Ah the option "when" was hard to see because it automatic opens the "file type" option.

**Comment by R0Wi** [comment] 2024-09-19 14:05
Doesn't [this](https://github.com/R0Wi-DEV/workflow_ocr/issues/41#issuecomment-744598185) work for you?
