### ISSUE TITLE
Groupfolders not working

### ISSUE THREAD

**Issue by thomasgg23** [R0Wi/workflow_ocr#23] opened 2020-10-03 15:02 UTC
Don't know if this is already known but the workflow_ocr doesn't work with files in groupfolders.
The workflow kicks in, but does not convert the pdf file.

Perhaps be related to this https://github.com/nextcloud/activity/pull/190/files

**Comment by bahnwaerter** [comment] 2020-10-03 15:22
Thanks for reporting this issue. @R0Wi and I will take a look at this issue.

**Comment by R0Wi** [comment] 2020-10-04 11:45
Hi @thomasgg23 i did a test on my local dev machine but i wasn't really able to reproduce the issue. The only thing i noticed in my `nextcloud.log` was:
```json
{
   "reqId":"RWBc5IpyQYI1g1Ze8LQS",
   "level":3,
   "time":"2020-10-04T11:30:00+00:00",
   "remoteAddr":"",
   "user":"test",
   "app":"PHP",
   "method":"",
   "url":"--",
   "message":{
      "Exception":"Error",
      "Message":"Trying to access array offset on value of type int at /var/www/html/nextcloud_git_19/lib/private/Files/Node/Node.php#328",
      "Code":0,
      "Trace":[
         {
            "file":"/var/www/html/nextcloud_git_19/lib/private/Files/Node/Node.php",
            "line":328,
            "function":"onError",
            "class":"OC\\Log\\ErrorHandler",
            "type":"::"
         },
         {
            "file":"/var/www/html/nextcloud_git_19/lib/private/Files/Node/Folder.php",
            "line":60,
            "function":"isValidPath",
            "class":"OC\\Files\\Node\\Node",
            "type":"->"
         },
         {
            "file":"/var/www/html/nextcloud_git_19/lib/private/Files/Node/Folder.php",
            "line":138,
            "function":"getFullPath",
            "class":"OC\\Files\\Node\\Folder",
            "type":"->"
         },
         {
            "file":"/var/www/html/nextcloud_git_19/apps/groupfolders/lib/Versions/VersionsBackend.php",
            "line":96,
            "function":"get",
            "class":"OC\\Files\\Node\\Folder",
            "type":"->"
         },
         {
            "file":"/var/www/html/nextcloud_git_19/apps/files_versions/lib/Versions/VersionManager.php",
            "line":93,
            "function":"createVersion",
            "class":"OCA\\GroupFolders\\Versions\\VersionsBackend",
            "type":"->"
         },
         {
            "file":"/var/www/html/nextcloud_git_19/apps/files_versions/lib/Storage.php",
            "line":207,
            "function":"createVersion",
            "class":"OCA\\Files_Versions\\Versions\\VersionManager",
            "type":"->"
         },
         {
            "file":"/var/www/html/nextcloud_git_19/apps/files_versions/lib/Hooks.php",
            "line":61,
            "function":"store",
            "class":"OCA\\Files_Versions\\Storage",
            "type":"::"
         },
         {
            "file":"/var/www/html/nextcloud_git_19/lib/private/legacy/OC_Hook.php",
            "line":110,
            "function":"write_hook",
            "class":"OCA\\Files_Versions\\Hooks",
            "type":"::"
         },
         {
            "file":"/var/www/html/nextcloud_git_19/lib/private/Files/View.php",
            "line":1274,
            "function":"emit",
            "class":"OC_Hook",
            "type":"::"
         },
         {
            "file":"/var/www/html/nextcloud_git_19/lib/private/Files/View.php",
            "line":1144,
            "function":"runHooks",
            "class":"OC\\Files\\View",
            "type":"->"
         },
         {
            "file":"/var/www/html/nextcloud_git_19/lib/private/Files/View.php",
            "line":696,
            "function":"basicOperation",
            "class":"OC\\Files\\View",
            "type":"->"
         },
         {
            "file":"/var/www/html/nextcloud_git_19/apps/workflow_ocr/lib/Wrapper/ViewWrapper.php",
            "line":43,
            "function":"file_put_contents",
            "class":"OC\\Files\\View",
            "type":"->"
         },
         {
            "file":"/var/www/html/nextcloud_git_19/apps/workflow_ocr/lib/BackgroundJobs/ProcessFileJob.php",
            "line":171,
            "function":"file_put_contents",
            "class":"OCA\\WorkflowOcr\\Wrapper\\ViewWrapper",
            "type":"->"
         },
         {
            "file":"/var/www/html/nextcloud_git_19/apps/workflow_ocr/lib/BackgroundJobs/ProcessFileJob.php",
            "line":96,
            "function":"processFile",
            "class":"OCA\\WorkflowOcr\\BackgroundJobs\\ProcessFileJob",
            "type":"->"
         },
         {
            "file":"/var/www/html/nextcloud_git_19/lib/private/BackgroundJob/Job.php",
            "line":62,
            "function":"run",
            "class":"OCA\\WorkflowOcr\\BackgroundJobs\\ProcessFileJob",
            "type":"->"
         },
         {
            "file":"/var/www/html/nextcloud_git_19/lib/private/BackgroundJob/QueuedJob.php",
            "line":46,
            "function":"execute",
            "class":"OC\\BackgroundJob\\Job",
            "type":"->"
         },
         {
            "file":"/var/www/html/nextcloud_git_19/cron.php",
            "line":126,
            "function":"execute",
            "class":"OC\\BackgroundJob\\QueuedJob",
            "type":"->"
         }
      ],
      "File":"/var/www/html/nextcloud_git_19/lib/private/Log/ErrorHandler.php",
      "Line":91,
      "CustomMessage":"--"
   },
   "userAgent":"--",
   "version":"19.0.4.0"
}
```

So it seems if there is an error while processing the file via `cron.php` after the new version of the file was written into the `groupfolder` but for me the new file-version was created nevertheless.

To provide further support could you please share the following information about your system:

- Nextcloud version
- Snippet of `nextcloud.log` file (usually found in `<NEXTCLOUD_ROOT>/data/nextcloud.log`) after `cron.php` has run. 
    - Upload a new pdf-file into the group folder
    - Log into the console of your Nextcloud server and change to the install directory of Nextcloud (where `cron.php` is located)
    - Run something like `sudo -u www-data php cron.php`
    - Share your logs

Thanks for your help!

**Comment by R0Wi** [comment] 2020-10-04 12:36
**Edit:** i think i found the culprit. The error i mentioned above disappears when applying the patch from https://github.com/nextcloud/groupfolders/pull/1029 so this was indeed an error inside the `groupfolders` app which was discussed [here](https://github.com/nextcloud/groupfolders/issues/1023). Unfortunately the fix ist not yet deployed to the NC appstore for Nextcloud version 19 (i checked that in code) it's currently only available in the latest `groupfolders` version `8.0.0` which is only compatible to NC 20.

If you're using NC19 you could do the following:
- Go onto your servers console
- Change into `<NEXTCLOUD_ROOT>/apps/groupfolders` 
- Run `curl -L https://github.com/nextcloud/groupfolders/pull/1029.patch | patch lib/Versions/VersionsBackend.php`

This worked for me on latest NC 19.

Let me know your results :-)

**Comment by thomasgg23** [comment] 2020-10-04 15:59
Yes works for me on NC 19.0.3 with group folders 7.0.0 and the patch applied.

**Comment by R0Wi** [comment] 2020-10-04 19:43
Closing since this was a bug in `groupfolders` app

**Closed by R0Wi** 2020-10-04 19:43 UTC
Labels: bug
