### ISSUE TITLE
Selected filter is not shown

### ISSUE THREAD

**Issue by mlsxlist** [R0Wi/workflow_ocr#71] opened 2021-10-31 07:47 UTC
After selecting a filter from the dropdown listbox, the selected filter value is not shown in the listbox. 

![image](https://user-images.githubusercontent.com/6071818/139573405-78e42b61-924e-4220-b755-279dde17bb52.png)

I am using Nextcloud 22.2.0 with the latest available Workflow OCR app from Nextcloud store. Browser is Firefox 78.15.0esr

**Comment by bahnwaerter** [comment] 2021-10-31 22:33
Hi @mlsxlist, thanks for reporting this issue.

I've set up a fresh Nextcloud 22.2.0 instance with the OCR workflow app in version 1.22.2 to check your reported problem. In this setup, the configuration of a user or system OCR workflow succeeds. Hence, I can't reproduce your configuration issue as the resulting and valid OCR workflow configuration shows:

![nc-22-2_workflow-ocr_configuration](https://user-images.githubusercontent.com/1800603/139601887-6ff324dd-dbdf-4410-a85a-976e8b00b024.png)

If I take a look at your screenshot, it seems like the graphical user interface of Nextcloud does not work properly in your browser. Have you accidentally blocked active web content (e.g. JavaScript) in your browser? So far, have you tried to reproduce your issue using another browser?

These questions aside, the user interface for all Nextcloud workflow apps is a part of the [Nextcloud Server](https://github.com/nextcloud/server). Therefore, user interface related issues do not affect the OCR workflow app and should be reported to the Nextcloud Server project. I close this issue since it is not part of the OCR workflow app and I can not reproduce it. Feel free to reopen this issue if we can help somehow.

**Closed by bahnwaerter** 2021-10-31 22:33 UTC

**Comment by mlsxlist** [comment] 2021-11-01 07:50
Thanks for looking into this. Created #29500

**Comment by bahnwaerter** [comment] 2021-11-01 13:28
@mlsxlist, thanks for reporting this issue to the Nextcloud core developer.

**Comment by bahnwaerter** [comment] 2021-11-01 13:30
For documentation purposes, I mark this issue as a duplicate of nextcloud/server#29500.
