### ISSUE TITLE
Unable to create flow - The given regular expression is invalid

### ISSUE THREAD

**Issue by hkdd** [R0Wi/workflow_ocr#67] opened 2021-09-24 20:42 UTC
Here's a screenshot:  https://i.imgur.com/7M5tRWL.png

When I try to create a new flow using the OCR app I get an error that "The given regular expression is invalid."  I'm selecting "File Created" under "When" and then specifying that it "matches" the "PDF documents" MIME type.  I've also tried as a test to just matching on a filename, but I get the same error.  

Nextcloud version is:  22.1.1

**Comment by R0Wi** [comment] 2021-09-24 20:59
I think this is a duplicate of https://github.com/R0Wi/workflow_ocr/issues/41?

**Closed** 2021-09-24 21:00 UTC
Labels: duplicate
