### ISSUE TITLE
OCR not working when Tag Assigned.

### ISSUE THREAD

**Issue by mudassir1996** [R0Wi/workflow_ocr#185] opened 2023-02-13 05:07 UTC
I have added a flow to OCR pdf files when the tag "OCR" is assigned but it doesn't work. Nothing appears in ```nextcloud.log``` as well.

![image](https://user-images.githubusercontent.com/22127299/218374716-17fc1b3a-1ceb-4e96-a189-e526489848ff.png)

It works when I set this flow

![image](https://user-images.githubusercontent.com/22127299/218375239-06fa9519-923f-41e5-b15c-b739ed9bd792.png)

But I want it to ocr when tag is assigned.

Versions I am using.
PHP: 7.4.3
Nextcloud: 22.2.10
ocrmypdf: 9.6.0
workflow_ocr: 1.22.5

**Comment by R0Wi** [comment] 2023-02-13 06:42
Hi @mudassir1996, please try to decrease your [loglevel](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html#log-level) to `0` and try again. After you have assigned a matching tag to a file, you should be able to see a log message starting with "onEvent: ...". If you don't see this message, then you're facing an issue related to the NC workflowengine, not this app itself. 

Otherwise, if you see the message from above, you should also be able to tell if the file was added to the job queue for next OCR processing. Either a log message like "Adding file to jobqueue: ..." should be visible or you should be able to tell why the file was not added.

**Comment by mudassir1996** [comment] 2023-02-13 07:08
I have decreased log level to 0 and set this flow.

![image](https://user-images.githubusercontent.com/22127299/218392605-d6fa9970-2ff4-4d8b-8dc7-f86e0782c79d.png)

Logs when I upload a pdf file.

```
[workflowengine] Debug: Flow activated by event \OCP\Files::postCreate

[workflow_ocr] Debug: onEvent: \OCP\Files::postCreate

[workflowengine] Debug: Flow activation: rules were requested for operation OCR file

[workflowengine] Debug: No flow configurations is going to run OCR file

```

Logs after cron runs

```
[workflowengine] Debug: Flow activated by event \OCP\Files::postCreate

[workflowengine] Debug: Cannot handle event \OCP\Files::postCreate of OC\EventDispatcher\GenericEventWrapper against entity OCA\WorkflowEngine\Entity\File and operation OCA\WorkflowOcr\Operation

[workflowengine] Info: Flow handling done for event \OCP\Files::postCreate

```

**Comment by R0Wi** [comment] 2023-02-13 07:41
> Logs when I upload a pdf file.

If I'm interpreting your screenshot correctly, you should not upload a file but rather assign the `OCR` tag to an existing (PDF-) file to trigger the workflow.

> `[workflowengine] Debug: No flow configurations is going to run OCR file`

Guess that's the reason why no matching flow was found. Please repeat your testing by assigning an existing tag to an existing file.

**Comment by mudassir1996** [comment] 2023-02-13 07:50
My mistake, I didn't add the log on tag assigned. Here are the logs

```
[workflowengine] Debug: Flow activated by event OCP\SystemTag\ISystemTagObjectMapper::assignTags
[workflow_ocr] Debug: onEvent: OCP\SystemTag\ISystemTagObjectMapper::assignTags
[workflowengine] Debug: Flow activation: rules were requested for operation OCR file
[workflowengine] Debug: No flow configurations is going to run OCR file
[workflow_ocr] Debug: Not processing event because IRuleMatcher->getFlows did not return anything

```

Tag I have assigned
![image](https://user-images.githubusercontent.com/22127299/218400301-4ac9ed62-52b4-49a1-ac77-6a0501dd157d.png)

**Comment by R0Wi** [comment] 2023-02-13 08:33
Ok that looks more meaningful now. The line

```
[workflow_ocr] Debug: Not processing event because IRuleMatcher->getFlows did not return anything
```

tells me that for some reason the NC workflowengine did not match the tag assignment to any existing rule. So indeed you could face an issues which has it's root cause inside NC itself. Could you try to setup the same rules for a different workflow (for example https://apps.nextcloud.com/apps/workflow_script) and see if it behaves the same? You could for example setup the script workflow with a script like this (please adjust the target path so that the executing cron user has permissions to write to the directory): 

```bash
echo "It works for %n" > /var/www/html/test.txt
```

After setup, if you've assigned the tag and run the `cron.php`, you should be able to see the `test.txt` file on your system. Please try that and post your logs here. If that works then the error is related to the OCR app, otherwise I guess there is some problem in the workflowengine itself, which cannot be fixed by us here.

**Comment by mudassir1996** [comment] 2023-02-13 09:14
It also does not work on tag assigned
```
[workflowengine] Info: Flow handling done for event OCP\SystemTag\ISystemTagObjectMapper::assignTags
[workflowengine] Debug: Flow activation: rules were requested for operation Run script
[workflowengine] Debug: No flow configurations is going to run Run script
```

But it does work on created, update etc

**Comment by R0Wi** [comment] 2023-02-13 09:22
Unfortunately I'm afraid there is not much we can do for you from the side of this app. You should raise a new issue at https://github.com/nextcloud/server/issues and link the one here, stating that your observed behaviour seems to be related to a bug inside of the workflowengine rule-matcher logic (which is independent of which concrete workflow app you're using). 

Please let us know if we can help you getting there. Closing this for the meantime.

**Closed by R0Wi** 2023-02-13 09:22 UTC
